image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: openjdk:8u232-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew test
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:
  stage: package
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - echo "$GOOGLE_KEY" | base64 -d > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set compute/zone europe-west1-b
    - gcloud config set project under-266013
    #- gcloud config set container/use_client_certificate true
    - gcloud container clusters get-credentials under-default
    - kubectl set image deployment/undersvc undersvc=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA